---
app_path: /docker/ha
puid: "{{ inventory__docker_puid }}"
pgid: "{{ inventory__docker_pgid }}"
tz: "{{ inventory__docker_tz }}"
app_network_name: "{{ inventory__docker_network }}"

homeassistant_image: homeassistant/home-assistant:latest
esphome_image: esphome/esphome:latest
frigate_image: ghcr.io/blakeblackshear/frigate:stable
mosquitto_image: eclipse-mosquitto:latest
grocy_image: linuxserver/grocy:latest
barcodebuddy_image: f0rc3/barcodebuddy:latest

homeassistant_config_path: "{{ app_path }}/homeassistant/config"
homeassistant_xiaomi_vacuum_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61626231353465646332323465306636346161363965616362633664666430663537383432336539
          3539356362313263666232646664653964636139326362330a656664663362633039323335646139
          64613635356330333939353539613162303330393663376263643761313038366663646564633335
          6335383430643233350a623234313737346363373637376632313231333235393565303864386538
          37346130643538356464373436626332323262343437373534386230306332396636626135316532
          3232333061383436656466646563316665613734383532663332
homeassistant_xiaomi_cloud_username: "{{ inventory__admin_mail }}"
homeassistant_xiaomi_cloud_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39353136313732656139363830303732626439633633323333306139323836333163386466303035
          6639376530346533373832353663366332323263363735370a623366656238316261356333303538
          37333338323165326365653766653933626635343861383932326563646363363432323934636632
          3037623830306434330a316532393165356637306339643862366136326330363336396238326530
          38646431306436353436633031356138623132646232646536333561613133383266

esphome_config_path: "{{ app_path }}/esphome/config"
esphome_wifi_ssid: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32363432316235636137323435653930313032616461323538336661646334636463333661613866
          6630643963323964326630653330613333636636356464610a666438353161383133666234613563
          62613761306364663863656134373038303065333834303134663133396638343330363139383432
          3264636233316561370a636234636564316436646131336437626339633532636538623861666264
          6262
esphome_wifi_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64656130373563356462326636373439633635353239623938373231336235643866643937623562
          3963393631316239363965633039623436663634613732610a323333343665363536333532353264
          65376261666463653266376561316539326333623136666134313531633132323130396530383138
          3464633438653739300a653031316433306564626636386634663134313864623637623138303830
          3532
esphome_wifi_ssid_dacha: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64366135363266636536613261396432323131323334656464366633633138626464336266333964
          3234373130646634393663316564323131313966646338320a333937653564663263656631313239
          38373935343064653461353937393739646334396436663236373539356465656663306530623663
          6161376139663630660a613462626164366263383466393835366562303132316339633361643035
          6163
esphome_wifi_hotspot_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35613738356438393365633538616437366538643763326537656163613664626466376332323261
          3965303962383330326131626237613462643032356661350a623665373839313034613936366432
          32313265323731336439303361343461363532303133666430633937643031653339666462643731
          3536613464666233380a356539636438613634303937613633326637376165623738333262663539
          3733

frigate_config_path: "{{ app_path }}/frigate/config"
frigate_media_path: "{{ app_path }}/frigate/media"
frigate_mqtt_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38363764663461616232316538313732383936313666376363663535623235356633383064616630
          3865343837343866343435373435303935633637313261650a633963353265656135326232313035
          32333236393338663435353265373565326639306566303139653538333365333030623731376465
          3536316364326434660a373466393764306537663435343565633264623236373531313066323732
          63646665646530373339363138616663613965633162383433666434343835373939
frigate_rtsp_password_bedroom: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30626532346261363364636665613466386662636534623437383961363765643963393532643539
          3730373238383831343465313064623533656465373130340a646133383532643133326638616566
          34393761623438346532643232353361643965363962633333376362393466636531643664326534
          6232643239636539320a353537613537643165663238653230363539646261396233366230323462
          6237
frigate_rtsp_password_living_room: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34643961326338643563666336353462626530666533383862336138616465643038366436313938
          6132666637636136383235363236663735666232653566360a333430303936343164316664373438
          35633737356235643732326130346232646363666134343839663361616232653134636135386337
          6439306536663532370a303236363363336535633861613633323161656465356464333030653963
          3266

mosquitto_data_path: "{{ app_path }}/mosquitto/data"
mosquitto_config_path: "{{ app_path }}/mosquitto/config"
mosquitto_password_file: "{{ mosquitto_config_path }}/password.txt"
