---
app_path: /docker/ha
puid: "{{ inventory__docker_puid }}"
pgid: "{{ inventory__docker_pgid }}"
tz: "{{ inventory__docker_tz }}"

esphome_image: esphome/esphome:latest
barcodebuddy_image: f0rc3/barcodebuddy-docker:latest
grocy_image: linuxserver/grocy:latest
homeassistant_image: homeassistant/home-assistant:latest

homeassistant_config_path: "{{ app_path }}/homeassistant/config"
homeassistant_telegram_bot_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61653966353566633632323538326365363033386534346534383131363939623334396161646164
          6261653537653161666239363638353162303165653966620a386430336362333132336161353261
          30353939336665626366613733356166393634663239363337303431373464623063343233623164
          3236323061373533320a383162663361333636653866323366386666666339343034313830323162
          63383263356435346538613534336265386430303661343535313630656536623335323537636134
          3161663034393432663063316165323130383931353034643539
homeassistant_telegram_bot_chat_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64313232646338343933623238666362323961316138386635643664646630393163363938643237
          3463343935343032646436626263613064613136303966300a396132613532396135356336333863
          61363065636163333365643331366163306439313236353961306430333937303038343932376532
          3936333263663237300a663064633036626532386137623166643232616564616266316461663466
          3931
homeassistant_xiaomi_vacuum_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61626231353465646332323465306636346161363965616362633664666430663537383432336539
          3539356362313263666232646664653964636139326362330a656664663362633039323335646139
          64613635356330333939353539613162303330393663376263643761313038366663646564633335
          6335383430643233350a623234313737346363373637376632313231333235393565303864386538
          37346130643538356464373436626332323262343437373534386230306332396636626135316532
          3232333061383436656466646563316665613734383532663332
homeassistant_xiaomi_cloud_username: "{{ inventory__admin_mail }}"
homeassistant_xiaomi_cloud_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39353136313732656139363830303732626439633633323333306139323836333163386466303035
          6639376530346533373832353663366332323263363735370a623366656238316261356333303538
          37333338323165326365653766653933626635343861383932326563646363363432323934636632
          3037623830306434330a316532393165356637306339643862366136326330363336396238326530
          38646431306436353436633031356138623132646232646536333561613133383266
