---
app_path: /docker/gw-wg

wg_pia_image: thrnz/docker-wireguard-pia:latest
wg_access_server_image: ghcr.io/freifunkmuc/wg-access-server:master
squid_image: ghcr.io/spirkaa/squid:latest

wg_pia_user: "{{ inventory__piavpn_user }}"
wg_pia_pass: "{{ inventory__piavpn_pass }}"
wg_pia_location: ee
wg_pia_local_network: 192.168.0.0/16
wg_pia_firewall: "0"
wg_pia_fwd_iface: eth0

wg_access_server_admin_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65336666396631663163306235666330666535643636326238646434376236333234316534383561
          3938366364646663323234643861326631323664343837310a313731636438613963316331363134
          65653837633638623630393965353462313966623337386562346232353739356535373630346132
          3866633937353864650a616132623632636532393435343732623632316437386332336633346263
          32336534656535653263366638356561633763663432303232396432643264623261
wg_access_server_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32623561303866613565316133356233623032396565346664336137636164616438656361613333
          3466333330303833643665383836633833383933336130370a343166346430353031613134313434
          33613065353534303163626339393036343264316366386139653037393133333539306262333763
          6532363735363431360a653435383838613939323163373338636431333030303438616533326635
          31633338356331653265333038373434333632616237373430643633386466313230306430356339
          6461643865376261653939626430643936366236323831363436

squid_config_path: "{{ app_path }}/squid/config"
squid_ldap_host: 192.168.11.2
squid_ldap_bind_dn: uid=squidsvc,{{ inventory__ldap_sysaccounts_dn }}
squid_ldap_bind_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39333861363537616339343665383236343064623434623465373834303163386163653162346231
          3136316539313234636564346439356433316330393133380a663533363064363861353962313537
          64303236336638316664353066323430323464343661633931653338613361616632336533376332
          3931333235306261370a393966316339666134346234303239326366353534333035373739303131
          61613031363363303866343164626566366361333236323861643439653262386237
squid_ldap_access_group: squid_users
squid_ldap_user_filter: (&(objectclass=inetorgperson)(memberof=cn={{ squid_ldap_access_group }},{{ inventory__ldap_groups_dn }})(uid=%s))
