---
- name: Install packages
  package:
    state: present
    name:
      - libpve-apiclient-perl
      - sudo

- name: Copy snmp extend scripts
  copy:
    src: files/extend
    dest: /etc/snmp
    mode: 0755
  notify: restart snmpd

- name: Copy smart.config
  template:
    src: templates/smart.config.j2
    dest: /etc/snmp/extend/smart.config
    mode: 0644
  notify: restart snmpd

- name: Copy sudoers.d file
  copy:
    src: files/snmp_sudo
    dest: /etc/sudoers.d
    mode: 0440

- name: Create a cron job
  cron:
    name: snmp_smart
    minute: "*/5"
    user: root
    job: "/etc/snmp/extend/smart -u"
    cron_file: snmp_smart

- name: Update snmpd.conf
  blockinfile:
    path: /etc/snmp/snmpd.conf
    block: |
      extend .1.3.6.1.4.1.2021.7890.1 distro /etc/snmp/extend/distro
      extend proxmox /usr/bin/sudo /etc/snmp/extend/proxmox
      extend smart /etc/snmp/extend/smart
      {% if inventory_hostname == "spsrv" %}
      extend ups-nut /etc/snmp/extend/ups-nut.sh
      {% endif %}
  notify: restart snmpd
