---
app_path: /docker/spnas
puid: "{{ inventory__docker_puid }}"
pgid: "{{ inventory__docker_pgid }}"
tz: "{{ inventory__docker_tz }}"

delugevpn_image: binhex/arch-delugevpn:2.0.5-1-04
jackett_image: linuxserver/jackett:development-v0.20.1261-ls494
prowlarr_image: linuxserver/prowlarr:nightly-0.4.2.1846-ls366
sonarr_image: linuxserver/sonarr:develop-3.0.8.1538-ls289
radarr_image: linuxserver/radarr:nightly-4.2.0.6396-ls327
lidarr_image: linuxserver/lidarr:nightly-1.1.0.2602-ls149
bazarr_image: linuxserver/bazarr:development-v1.0.5-beta.39-ls360
muximux_image: linuxserver/muximux:version-418923c8
flaresolverr_image: flaresolverr/flaresolverr:v2.2.4
monitorrent_image: werwolfby/alpine-monitorrent:1.1.12
nextcloud_db_image: postgres:14-alpine
nextcloud_image: ghcr.io/wonderfall/nextcloud:24
samba_image: mbentley/timemachine:smb
minio_image: minio/minio:RELEASE.2022-06-30T20-58-09Z

app_network_name: "{{ inventory__docker_network }}"

muximux_www: "{{ app_path }}/muximux/config/www"

delugevpn_vpn_user: "{{ inventory__piavpn_user }}"
delugevpn_vpn_pass: "{{ inventory__piavpn_pass }}"

samba_mimic_model: Xserve
samba_user: spirkaa
samba_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61303964323933356337643731316135666630386239323463393564306536653635323062636134
          3135643562623236646462626630633261383833623061350a343039633335646331613636343062
          32343165313730383266373661323138646430313835653664346236373533386130613835656437
          3762373839653961650a393235333933616334623136376231363936363133326666613830336437
          6630

nextcloud_db_root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33366465383036646331613332333265303161383235383364323636326231346139326437383937
          6139363161666562353436373864363966363731636632660a613966363935616461623565613033
          62663235313537303539316237626632633065616632393138393633363338386164666630643561
          6532323962323563650a663537626333343137346366363461623963326138303634343337383966
          62343037383162323036613030663432353339646232613361633437373436656233
nextcloud_db_user: nextcloud
nextcloud_db_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38636537353963656533643235613561653838363366666435636232326163323138313666363365
          3131616134373166346335616434333635656530623136330a353765666333613931656330373435
          62353032333739363538633731336565623264333863643636646133346636643431353937356463
          3462666332643461370a336137643338393562333461613130363362303266326338383438396531
          64353363613164633134393663663339366236366237653563336130316264363131
nextcloud_ldap_bind_dn: uid=nextcloudsvc,{{ inventory__ldap_sysaccounts_dn }}
nextcloud_ldap_bind_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32366633336164623634356639326430636433333435636261663762353633313931626234313437
          6164366630393765386636356333353766663736326437340a353963653830666533323636316461
          38313966303434383964316563623337396430346134313737363135666535333535623134313230
          3230366437326338330a666136353639316438363030343831653034343763343135396133623835
          64623431333030636366643066343435633462393530316161333562643765383861
nextcloud_ldap_access_group: nextcloud_users

minio_server_url: https://s3.{{ inventory__site }}
minio_browser_redirect_url: https://minio.{{ inventory__homelab_domain }}
minio_root_user: minio
minio_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35663537313734356533306335323263663034626361323930333730366562306264623831663530
          3536393433613935376362643631646565663865376235640a313166313537636335636461616361
          34653736623533653638333765373739396334633462376465383664333664363831643866623335
          3065666431386662630a326135396139613730613736393836326537303062346535373335336263
          32663030623865323736613432616136306538613831303836643664616566666638626130616636
          6332333166343635386231353935326562393535613766616339
