---
- name: homeassistant
  ansible.builtin.include_tasks: homeassistant.yml
  tags: homeassistant

- name: esphome
  ansible.builtin.include_tasks: esphome.yml
  tags: esphome

- name: frigate
  ansible.builtin.include_tasks: frigate.yml
  tags: frigate

- name: mosquitto
  ansible.builtin.include_tasks: mosquitto.yml
  tags: mosquitto

- name: grocy
  ansible.builtin.include_tasks: grocy.yml
  tags: grocy
