---
tz: "Europe/Moscow"

app_path: /docker/gia-api
app_network_name: traefik
app_base_domain: home.devmem.ru

registry: registry.{{ app_base_domain }}

gia_repo: "{{ registry }}/gia"
gia_db_image: "{{ gia_repo }}/postgres:latest"
gia_redis_image: "{{ gia_repo }}/redis:latest"
gia_api_image: "{{ gia_repo }}/api:latest"
gia_front_image: "{{ gia_repo }}/front:latest"

gia_network: gia
gia_db_user: gia
gia_db_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61643736616263313231366636613662356635376663626434376138323262663931306265323733
          6330346233313230383638343130633566363536613335360a363862316534353665616639653064
          37623666383235666239666238356534613061633736346337626434303661653864353562366630
          3764633937616235630a333861353163653432643363623765316438343831326631326365323339
          6461
gia_api_django_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34633765363530303737326264623262663063373663363638646464313635373834656266346363
          6463323434386638663638633635643335653133323533380a323561363563373664623634376539
          31363733393464303665396237663532613463366231346233356334643839633432333431666334
          3066643163393364380a323938373461343963666366656261626666376433643965353631656466
          37616234316561376366636161393639373437346338303762316636376166303865303132396438
          38343337383164643466663039616363666436613732393564373335356337633134656333326363
          646537323334633162346461643936656230
gia_api_django_allowed_hosts: .devmem.ru

smtp_host: smtp.devmem.ru
smtp_port: "587"
smtp_user: noreply@devmem.ru
smtp_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34383138383533303362626662626235653861616339643536323465373262303064316365666365
          6535356536323436383364633432316138653939346331620a623164643030313564653936323763
          34303431343461313561626366356665343135383232653363636364653862323133616533393761
          3164303233343337650a656338386335616630343137343735316238663032633533366262393137
          61613737396330356538333530636162623131376334373065333237633936366561
