---
- name: Get pveversion for backup filename
  shell: "pveversion | awk -F / '{print $2}'"
  register: pveversion
  changed_when: false

- name: Check if backup file exists
  stat:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak-{{ pveversion.stdout }}"
  register: proxmoxlib_backup

- block:
  - name: Make a backup of original file
    copy:
      remote_src: True
      src: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
      dest: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak-{{ pveversion.stdout }}"

  # credit: https://johnscs.com/remove-proxmox51-subscription-notice/
  - name: Modify line in file to remove nag message  # noqa 303
    shell:
      cmd: |
        sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    notify: restart pveproxy
    args:
      warn: no
  when: not proxmoxlib_backup.stat.exists

- name: Change Proxmox replication interval
  lineinfile:
    path: /lib/systemd/system/pvesr.timer
    regexp: "^OnCalendar=minutely"
    line: "OnCalendar=hourly"
  notify: reload pvesr
