---
openwrt_dnsmasq:
  authoritative: 0

openwrt_dhcp:
  force: 0
  ignore: 1

openwrt_wireguard:
  - interface: wg0
    server: true
    listen_port: 51821
    addresses:
      - 10.44.0.1/24
    public_key: 10IYGaK04ISwjBPMfxcNMfZGMfmHl+Vd9eY3ePVV3hw=
    private_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      32393963396535633031386232366430306262363266356436366631326463663064373938353537
      3636653137643064336135386438393837376639316638360a633266386466306438646233366630
      35373263376239353432373362373463633233643635663561616132393963346431663236663564
      3961313563376566620a636235663735383565633765653932313438646331336431303336303962
      35616361383830653565316365356238653762383733613831396635623130336331636662396666
      3463646464346330623565383737333735626238316465623136
    peers:
      - description: spgalaxy
        allowed_ips:
          - 10.44.0.2/32
        public_key: 7MEJZ4P8XYVlhQTcuOXN6oQdeevKXOdHjps/GSUt90o=
        private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62376563303564366135626439666331653133613530333066366330373761343532616332363561
          3238633665316131363664666433636136343231636330630a653962633637366266623339323937
          39323463636137333230373233386161313032633530666538353834363038373662646435633235
          6435353164316361300a633666363063383233643934393835333034353831323933646364663762
          62663939653061306462323033643837303538363637346239323066613864663836353139666363
          3735643762393332633364383139626162353862653039646630
      - description: iphone
        allowed_ips:
          - 10.44.0.3/32
        public_key: dNpZeVI8rA0rHaZuW9IKtGVmyRPXM7viiSVzIVm1qCQ=
        private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35393763616233653963623930346132383539333130373666626538356531666561626265366134
          6666306264393532616433656331383334323736643831610a323335636164376338386531373165
          32356539336665313162663034346439386434356135316165633331623130616563626530656133
          3065356364343832390a356632313932303837343137346236636339623433323865643764613833
          64383066383039643634336166646433363731653163313765616262313939363239323161383764
          3030396430646466653562643832316466346632396333623661
      - description: deluge
        allowed_ips:
          - 10.44.0.4/32
        public_key: BZGmOWXPm86fSQfCqQkEXEoLv43ocpS/8R2CuHb5oG8=
        private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37613439636165313934633463663234303838383433633134303133313261396264613063616238
          3530656532666531333338613633333461646130623964310a663739616237303261653231313465
          65613336363065363233623236343033336332386264336430356339396636373331333534646166
          6565636162323038360a343037363232643861393539313966366535313736393766643161393034
          61383839653632336665326131363862653164366366663633396561326463613632336661623038
          3062393435333365363335633032663966353264653736656538
      - description: spmacbook
        allowed_ips:
          - 10.44.0.5/32
        public_key: okOdos3cbuHz3P2TF420HQqR+wDA0HpBOMIQVoXNti4=
        private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39366136626131386439323438306133376439366364353230393831666534323830636534613834
          3437326431326633363332353762393434303335303565640a333032343038333164373066353435
          34333261613231313734343536313437303939393466613561353230616539303637636164303763
          6337613239623632350a316165396138353765343131306161386632353835316236633231623131
          65356630383064623663313930343233393737393633663639366138643932646361383039346636
          3337643538323637633366313436636435326238306338626465
      - description: spipad
        allowed_ips:
          - 10.44.0.6/32
        public_key: Z9hzkmp0VQK8JbmB1AdAfkfojnkkTVK4FP/NGHkcb00=
        private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35613137623634636334313538336438636466383365646530653338386434613839623063333638
          6433376539646162643231643733646635343933376564390a333334616266663361373633326561
          37316134396539636464306435306231363933666334616136323831633132633133306432666636
          6430613561343436310a633935386463663261663039333665333165396663653562363930626132
          31343935333763346364336236353236313135353566353230356331666633336131383434383130
          3965313639616164313332326239666531666139326336323532

  - interface: wg1
    firewall_zone: lan
    addresses:
      - 10.255.255.11/32
    public_key: FAzXW6hJ7Gb/83ZFcGCyktSVil13/SKvOHBDMYeR2C8=
    private_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38386462623938386439373037386232623164343634623033373434313965653135636438336235
      3432663036663037383932396564376530363731313663300a316362396237383962303165303364
      31383939643736373666633539376366303662636661666434316366633231363063346261376633
      6236353462396663350a366663383335616332633762393030333936333862346336643966666130
      36353862333066316136623166663634343534363830313061353832353333326563393633336365
      3637653738633838326464336366663534346536643339356462
    peers:
      - description: vps-sber1
        allowed_ips:
          - 0.0.0.0/0
          - 10.255.255.1/32
        public_key: ptgafvY1m2aj4FKFwBCeEVylpPjaynqEYm0tQyR3P2c=
        endpoint_host: vps-sber1.devmem.ru
        endpoint_port: 51820
        persistent_keepalive: 10
