---
snmp_syslocation: sale-dedic.com

vps_wg_interface: wg1
vps_wg_private_ip: 10.255.254.1
vps_wg_privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62336162343165626332666539353463633937613165666238653138353934316239383264316266
          3132626665626662623735643663353537663339316564610a353261656234383564636461613033
          63366166616438353234393137306139666137623463316464333935333230393439383136353662
          6361353061616330630a383839383065623263646664373466666536636166323365656434396163
          61653162393865656334326430623832383863376231656439636434366433346634346266343361
          6366323564363036323161633736353734646238653533666266
vps_wg_pubkey: N+/pBa/Q6KoSanuTyGiIYweh9MYzuF8naR3oB6F7SSE=
vps_wg_peers:
  - name: vps-sber1
    pubkey: fZyaKWUEe5MAHUQkiimffxV6P3IBQus091665UEN0S4=
    private_ip: 10.255.254.2
    state: present

wg_pia_enabled: true
sing_box_enabled: true
